# Generated by Django 2.2.14 on 2020-07-21 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_id',
        ),
    ]
