# Generated by Django 2.2.14 on 2020-07-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200721_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='destaques',
            field=models.CharField(choices=[('Imperdíveis', 'Imperdíveis'), ('Nossas Ofertas', 'Nossas Ofertas'), ('Destaques', 'Destaques')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Tênis', 'Tênis'), ('Chuteira', 'Chuteira'), ('Calçados', 'Calçados')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Infantil', 'Infantil')], max_length=20),
        ),
    ]
