# Generated by Django 2.2.14 on 2020-07-21 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200721_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='destaques',
            new_name='group',
        ),
    ]
