# Generated by Django 2.2.14 on 2020-07-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200721_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=20, verbose_name=('Tenis', 'Chuteira', 'Calcados')),
        ),
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.CharField(choices=[('Imperdiveis', 'Imperdiveis'), ('Nossas Ofertas', 'Nossas Ofertas'), ('Destaques', 'Destaques')], max_length=20),
        ),
    ]
