# Generated by Django 2.2.14 on 2020-07-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200722_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Tenis', 'Tenis'), ('Chuteira', 'Chuteira'), ('Calcados', 'Calcados')], max_length=20),
        ),
    ]
