# Generated by Django 2.2.14 on 2020-07-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200722_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Tenis', 'Tenis'), ('Chuteiras', 'Chuteiras'), ('Calcados', 'Calcados')], max_length=20),
        ),
    ]
