# Generated by Django 2.2.14 on 2020-07-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200726_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mobile', models.BooleanField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
